// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJEphJoCEpEYKqupgFZoDW2-Zqp3L0en8',
    appId: '1:875280985769:web:4ccb286f9316206e7dc3b8',
    messagingSenderId: '875280985769',
    projectId: 'volunteer-connect-4664c',
    authDomain: 'volunteer-connect-4664c.firebaseapp.com',
    storageBucket: 'volunteer-connect-4664c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBctthx5jx_jQ7BtarrnAigxwixLyAoFeA',
    appId: '1:875280985769:android:183c2cf3a7ed61137dc3b8',
    messagingSenderId: '875280985769',
    projectId: 'volunteer-connect-4664c',
    storageBucket: 'volunteer-connect-4664c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4BuyWQ6XFo55a_kQ4GPc5sAylNdk4kR0',
    appId: '1:875280985769:ios:71407756299bf4927dc3b8',
    messagingSenderId: '875280985769',
    projectId: 'volunteer-connect-4664c',
    storageBucket: 'volunteer-connect-4664c.appspot.com',
    iosBundleId: 'com.example.vcV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4BuyWQ6XFo55a_kQ4GPc5sAylNdk4kR0',
    appId: '1:875280985769:ios:47b0ec0437990d147dc3b8',
    messagingSenderId: '875280985769',
    projectId: 'volunteer-connect-4664c',
    storageBucket: 'volunteer-connect-4664c.appspot.com',
    iosBundleId: 'com.example.vcV1.RunnerTests',
  );
}
